#include "../header/auxiliary.h"
#include "../header/configs.h"
#include "../header/SampleRenderer.h"
// this include may only appear in a single source file:
#include <optix_function_table_definition.h>

// import ptx generated by bin2c
#include "../ptx/devicePrograms.h"

#include <cuda.h>

/*! \namespace osc - Optix Siggraph Course */
namespace osc
{
  // /*! generated from base name component of source file
  //     (devicePrograms.cu), plus "_ptx" */
  // extern "C" char devicePrograms_ptx[];

  /*! SBT record for a raygen program */
  struct __align__(OPTIX_SBT_RECORD_ALIGNMENT) RaygenRecord
  {
    __align__(OPTIX_SBT_RECORD_ALIGNMENT) char header[OPTIX_SBT_RECORD_HEADER_SIZE];
    // just a dummy value - later examples will use more interesting
    // data here
    void *data;
  };

  /*! SBT record for a miss program */
  struct __align__(OPTIX_SBT_RECORD_ALIGNMENT) MissRecord
  {
    __align__(OPTIX_SBT_RECORD_ALIGNMENT) char header[OPTIX_SBT_RECORD_HEADER_SIZE];
    // just a dummy value - later examples will use more interesting
    // data here
    void *data;
  };

  /*! SBT record for a hitgroup program */
  struct __align__(OPTIX_SBT_RECORD_ALIGNMENT) HitgroupRecord
  {
    __align__(OPTIX_SBT_RECORD_ALIGNMENT) char header[OPTIX_SBT_RECORD_HEADER_SIZE];
    // just a dummy value - later examples will use more interesting
    // data here
    int objectID;
  };

  /*! helper function that initializes optix and checks for errors */
  void SampleRenderer::initOptix()
  {
    std::cout << "#osc: initializing optix..." << std::endl;

    // -------------------------------------------------------
    // check for available optix7 capable devices
    // -------------------------------------------------------
    cudaFree(0);
    int numDevices;
    cudaGetDeviceCount(&numDevices);
    if (numDevices == 0)
      throw std::runtime_error("#osc: no CUDA capable devices found!");
    std::cout << "#osc: found " << numDevices << " CUDA devices" << std::endl;

    // -------------------------------------------------------
    // initialize optix
    // -------------------------------------------------------
    OPTIX_CHECK(optixInit());
  }

  static void context_log_cb(unsigned int level,
                             const char *tag,
                             const char *message,
                             void *)
  {
    fprintf(stderr, "[%2d][%12s]: %s\n", (int)level, tag, message);
  }

  /*! creates and configures a optix device context (in this simple
      example, only for the primary GPU device) */
  void SampleRenderer::createContext()
  {
    // for this sample, do everything on one device
    const int deviceID = 0;
    CUDA_CHECK(SetDevice(deviceID));
    CUDA_CHECK(StreamCreate(&stream));

    cudaGetDeviceProperties(&deviceProps, deviceID);
    std::cout << "#osc: running on device: " << deviceProps.name << std::endl;

    CUresult cuRes = cuCtxGetCurrent(&cudaContext);
    if (cuRes != CUDA_SUCCESS)
      fprintf(stderr, "Error querying current context: error code %d\n", cuRes);

    OPTIX_CHECK(optixDeviceContextCreate(cudaContext, 0, &optixContext));
    OPTIX_CHECK(optixDeviceContextSetLogCallback(optixContext, context_log_cb, nullptr, 4));
  }

  /*! creates the module that contains all the programs we are going
      to use. in this simple example, we use a single module from a
      single .cu file, using a single embedded ptx string */
  void SampleRenderer::createModule()
  {
    moduleCompileOptions.maxRegisterCount = 50;

    // [debug]

    // moduleCompileOptions.optLevel = OPTIX_COMPILE_OPTIMIZATION_LEVEL_0;
    // moduleCompileOptions.debugLevel = OPTIX_COMPILE_DEBUG_LEVEL_FULL;

    // [release]
    moduleCompileOptions.optLevel = OPTIX_COMPILE_OPTIMIZATION_DEFAULT;
    moduleCompileOptions.debugLevel = OPTIX_COMPILE_DEBUG_LEVEL_NONE;

    // moduleCompileOptions.optLevel = OPTIX_COMPILE_OPTIMIZATION_LEVEL_3; // not much improvement

    pipelineCompileOptions = {};
    pipelineCompileOptions.traversableGraphFlags = OPTIX_TRAVERSABLE_GRAPH_FLAG_ALLOW_SINGLE_GAS;
    pipelineCompileOptions.usesMotionBlur = false;
    pipelineCompileOptions.numPayloadValues = PAYLOAD_COUNT_TO_USE;

    // [should use this when distribute the code]
    pipelineCompileOptions.exceptionFlags = OPTIX_EXCEPTION_FLAG_NONE;
    // pipelineCompileOptions.exceptionFlags = OPTIX_EXCEPTION_FLAG_TRACE_DEPTH;
    // [use this during developing]
    // log=Warning: use of OPTIX_EXCEPTION_FLAG_DEBUG is deprecated. Use OPTIX_DEVICE_CONTEXT_VALIDATION_MODE_ALL instead.
    // pipelineCompileOptions.exceptionFlags = OPTIX_EXCEPTION_FLAG_DEBUG;

    pipelineCompileOptions.pipelineLaunchParamsVariableName = "optixLaunchParams";

    // only call optixTrace() once for 0-bounce
    // for iterative path tracing, it should also be 1
    pipelineLinkOptions.maxTraceDepth = 1;

    char log[2048];
    size_t sizeof_log = sizeof(log);
    OPTIX_CHECK(optixModuleCreate(optixContext,
                                  &moduleCompileOptions,
                                  &pipelineCompileOptions,
                                  reinterpret_cast<const char *>(devicePrograms_ptx),
                                  sizeof(devicePrograms_ptx),
                                  log, &sizeof_log,
                                  &module));
  }

  /*! does all setup for the raygen program(s) we are going to use */
  void SampleRenderer::createRaygenPrograms()
  {
    // should change to the count of raygen programs
    raygenPGs.resize(7);

    OptixProgramGroupOptions pgOptions_nobounce = {};
    OptixProgramGroupDesc pgDesc_nobounce = {};
    pgDesc_nobounce.kind = OPTIX_PROGRAM_GROUP_KIND_RAYGEN;
    pgDesc_nobounce.raygen.module = module;
    pgDesc_nobounce.raygen.entryFunctionName = "__raygen__nobounce";

    OptixProgramGroupOptions pgOptions_singlebounce = {};
    OptixProgramGroupDesc pgDesc_singlebounce = {};
    pgDesc_singlebounce.kind = OPTIX_PROGRAM_GROUP_KIND_RAYGEN;
    pgDesc_singlebounce.raygen.module = module;
    pgDesc_singlebounce.raygen.entryFunctionName = "__raygen__singlebounce";

    OptixProgramGroupOptions pgOptions_pathtracing = {};
    OptixProgramGroupDesc pgDesc_pathtracing = {};
    pgDesc_pathtracing.kind = OPTIX_PROGRAM_GROUP_KIND_RAYGEN;
    pgDesc_pathtracing.raygen.module = module;
    pgDesc_pathtracing.raygen.entryFunctionName = "__raygen__pathtracing";

    OptixProgramGroupOptions pgOptions_materialpass = {};
    OptixProgramGroupDesc pgDesc_materialpass = {};
    pgDesc_materialpass.kind = OPTIX_PROGRAM_GROUP_KIND_RAYGEN;
    pgDesc_materialpass.raygen.module = module;
    pgDesc_materialpass.raygen.entryFunctionName = "__raygen__materialpass";

    OptixProgramGroupOptions pgOptions_nobounce_backward = {};
    OptixProgramGroupDesc pgDesc_nobounce_backward = {};
    pgDesc_nobounce_backward.kind = OPTIX_PROGRAM_GROUP_KIND_RAYGEN;
    pgDesc_nobounce_backward.raygen.module = module;
    pgDesc_nobounce_backward.raygen.entryFunctionName = "__raygen__nobounce_backward";

    OptixProgramGroupOptions pgOptions_singlebounce_backward = {};
    OptixProgramGroupDesc pgDesc_singlebounce_backward = {};
    pgDesc_singlebounce_backward.kind = OPTIX_PROGRAM_GROUP_KIND_RAYGEN;
    pgDesc_singlebounce_backward.raygen.module = module;
    pgDesc_singlebounce_backward.raygen.entryFunctionName = "__raygen__singlebounce_backward";

    OptixProgramGroupOptions pgOptions_materialpass_backward = {};
    OptixProgramGroupDesc pgDesc_materialpass_backward = {};
    pgDesc_materialpass_backward.kind = OPTIX_PROGRAM_GROUP_KIND_RAYGEN;
    pgDesc_materialpass_backward.raygen.module = module;
    pgDesc_materialpass_backward.raygen.entryFunctionName = "__raygen__materialpass_backward";

    // OptixProgramGroup raypg;
    char log[2048];
    size_t sizeof_log = sizeof(log);

    // [forward]

    OPTIX_CHECK(optixProgramGroupCreate(optixContext,
                                        &pgDesc_nobounce,
                                        1,
                                        &pgOptions_nobounce,
                                        log, &sizeof_log,
                                        &raygenPGs[0]));
    OPTIX_CHECK(optixProgramGroupCreate(optixContext,
                                        &pgDesc_singlebounce,
                                        1,
                                        &pgOptions_singlebounce,
                                        log, &sizeof_log,
                                        &raygenPGs[1]));
    OPTIX_CHECK(optixProgramGroupCreate(optixContext,
                                        &pgDesc_pathtracing,
                                        1,
                                        &pgOptions_pathtracing,
                                        log, &sizeof_log,
                                        &raygenPGs[2]));
    OPTIX_CHECK(optixProgramGroupCreate(optixContext,
                                        &pgDesc_materialpass,
                                        1,
                                        &pgOptions_materialpass,
                                        log, &sizeof_log,
                                        &raygenPGs[5]));

    // [backward]

    OPTIX_CHECK(optixProgramGroupCreate(optixContext,
                                        &pgDesc_nobounce_backward,
                                        1,
                                        &pgOptions_nobounce_backward,
                                        log, &sizeof_log,
                                        &raygenPGs[3]));
    OPTIX_CHECK(optixProgramGroupCreate(optixContext,
                                        &pgDesc_singlebounce_backward,
                                        1,
                                        &pgOptions_singlebounce_backward,
                                        log, &sizeof_log,
                                        &raygenPGs[4]));
    OPTIX_CHECK(optixProgramGroupCreate(optixContext,
                                        &pgDesc_materialpass_backward,
                                        1,
                                        &pgOptions_materialpass_backward,
                                        log, &sizeof_log,
                                        &raygenPGs[6]));

    if (sizeof_log > 1)
      PRINT(log);
  }

  /*! does all setup for the miss program(s) we are going to use */
  void SampleRenderer::createMissPrograms()
  {
    // we do a single ray gen program in this example:
    missPGs.resize(1);

    OptixProgramGroupOptions pgOptions = {};
    OptixProgramGroupDesc pgDesc = {};
    pgDesc.kind = OPTIX_PROGRAM_GROUP_KIND_MISS;
    pgDesc.miss.module = module;
    pgDesc.miss.entryFunctionName = "__miss__ms";

    // OptixProgramGroup raypg;
    char log[2048];
    size_t sizeof_log = sizeof(log);
    OPTIX_CHECK(optixProgramGroupCreate(optixContext,
                                        &pgDesc,
                                        1,
                                        &pgOptions,
                                        log, &sizeof_log,
                                        &missPGs[0]));
    if (sizeof_log > 1)
      PRINT(log);
  }

  /*! does all setup for the hitgroup program(s) we are going to use */
  void SampleRenderer::createHitgroupPrograms()
  {
    // for this simple example, we set up a single hit group
    hitgroupPGs.resize(1);

    OptixProgramGroupOptions pgOptions = {};
    OptixProgramGroupDesc pgDesc = {};
    pgDesc.kind = OPTIX_PROGRAM_GROUP_KIND_HITGROUP;
    pgDesc.hitgroup.moduleCH = module;
    pgDesc.hitgroup.entryFunctionNameCH = "__closesthit__ch";
    pgDesc.hitgroup.moduleAH = module;
    pgDesc.hitgroup.entryFunctionNameAH = "__anyhit__ah";

    char log[2048];
    size_t sizeof_log = sizeof(log);
    OPTIX_CHECK(optixProgramGroupCreate(optixContext,
                                        &pgDesc,
                                        1,
                                        &pgOptions,
                                        log, &sizeof_log,
                                        &hitgroupPGs[0]));
    if (sizeof_log > 1)
      PRINT(log);
  }

  /*! assembles the full pipeline of all programs */
  void SampleRenderer::createPipeline()
  {
    std::vector<OptixProgramGroup> programGroups;
    for (auto pg : raygenPGs)
      programGroups.push_back(pg);
    for (auto pg : missPGs)
      programGroups.push_back(pg);
    for (auto pg : hitgroupPGs)
      programGroups.push_back(pg);

    char log[2048];
    size_t sizeof_log = sizeof(log);
    OPTIX_CHECK(optixPipelineCreate(optixContext,
                                    &pipelineCompileOptions,
                                    &pipelineLinkOptions,
                                    programGroups.data(),
                                    (int)programGroups.size(),
                                    log, &sizeof_log,
                                    &pipeline));
    if (sizeof_log > 1)
      PRINT(log);

    OPTIX_CHECK(optixPipelineSetStackSize(/* [in] The pipeline to configure the stack size for */
                                          pipeline,
                                          /* [in] The direct stack size requirement for direct
                                             callables invoked from IS or AH. */
                                          2 * 1024,
                                          /* [in] The direct stack size requirement for direct
                                             callables invoked from RG, MS, or CH.  */
                                          2 * 1024,
                                          /* [in] The continuation stack requirement. */
                                          2 * 1024,
                                          /* [in] The maximum depth of a traversable graph
                                             passed to trace. */
                                          1));
    if (sizeof_log > 1)
      PRINT(log);
  }

  /*! constructs the shader binding table */
  void SampleRenderer::buildSBT()
  {
    // ------------------------------------------------------------------
    // build raygen records
    // ------------------------------------------------------------------
    std::vector<RaygenRecord> raygenRecords;
    for (int i = 0; i < static_cast<int>(raygenPGs.size()); i++)
    {
      RaygenRecord rec;
      OPTIX_CHECK(optixSbtRecordPackHeader(raygenPGs[i], &rec));
      rec.data = nullptr; /* for now ... */
      raygenRecords.push_back(rec);
    }
    raygenRecordsBuffer.alloc_and_upload(raygenRecords);

    // // NOTE: select different raygen programs in the render() function
    // const int chosen_raygen_program = 1;
    // sbt.raygenRecord = raygenRecordsBuffer.d_pointer() + chosen_raygen_program * sizeof(RaygenRecord);

    // ------------------------------------------------------------------
    // build miss records
    // ------------------------------------------------------------------
    std::vector<MissRecord> missRecords;
    for (int i = 0; i < static_cast<int>(missPGs.size()); i++)
    {
      MissRecord rec;
      OPTIX_CHECK(optixSbtRecordPackHeader(missPGs[i], &rec));
      rec.data = nullptr; /* for now ... */
      missRecords.push_back(rec);
    }
    missRecordsBuffer.alloc_and_upload(missRecords);
    sbt.missRecordBase = missRecordsBuffer.d_pointer();
    sbt.missRecordStrideInBytes = sizeof(MissRecord);
    sbt.missRecordCount = (int)missRecords.size();

    // ------------------------------------------------------------------
    // build hitgroup records
    // ------------------------------------------------------------------

    // we don't actually have any objects in this example, but let's
    // create a dummy one so the SBT doesn't have any null pointers
    // (which the sanity checks in compilation would complain about)
    int numObjects = 1;
    std::vector<HitgroupRecord> hitgroupRecords;
    for (int i = 0; i < numObjects; i++)
    {
      int objectType = 0;
      HitgroupRecord rec;
      OPTIX_CHECK(optixSbtRecordPackHeader(hitgroupPGs[objectType], &rec));
      rec.objectID = i;
      hitgroupRecords.push_back(rec);
    }
    hitgroupRecordsBuffer.alloc_and_upload(hitgroupRecords);
    sbt.hitgroupRecordBase = hitgroupRecordsBuffer.d_pointer();
    sbt.hitgroupRecordStrideInBytes = sizeof(HitgroupRecord);
    sbt.hitgroupRecordCount = (int)hitgroupRecords.size();
  }

  // --------

  /*! constructor - performs all setup, including initializing
    optix, creates module, pipeline, programs, SBT, etc. */
  SampleRenderer::SampleRenderer()
  {
    initOptix();

    std::cout << "#osc: creating optix context ..." << std::endl;
    createContext();

    std::cout << "#osc: setting up module ..." << std::endl;
    createModule();

    std::cout << "#osc: creating raygen programs ..." << std::endl;
    createRaygenPrograms();
    std::cout << "#osc: creating miss programs ..." << std::endl;
    createMissPrograms();
    std::cout << "#osc: creating hitgroup programs ..." << std::endl;
    createHitgroupPrograms();

    std::cout << "#osc: setting up optix pipeline ..." << std::endl;
    createPipeline();

    std::cout << "#osc: building SBT ..." << std::endl;
    buildSBT();

    launchParamsBuffer.alloc(sizeof(launchParams));
    std::cout << "#osc: context, module, pipeline, etc, all set up ..." << std::endl;
  }

  SampleRenderer::~SampleRenderer()
  {
    std::cout << "#osc: called ~SampleRenderer() ..." << std::endl;

    // Program groups
    for (auto pg : raygenPGs)
      if (pg)
        OPTIX_CHECK(optixProgramGroupDestroy(pg));

    for (auto pg : missPGs)
      if (pg)
        OPTIX_CHECK(optixProgramGroupDestroy(pg));

    for (auto pg : hitgroupPGs)
      if (pg)
        OPTIX_CHECK(optixProgramGroupDestroy(pg));

    // Pipeline and module
    if (pipeline)
      OPTIX_CHECK(optixPipelineDestroy(pipeline));

    if (module)
      OPTIX_CHECK(optixModuleDestroy(module));

    // SBT / device buffers
    raygenRecordsBuffer.free();
    missRecordsBuffer.free();
    hitgroupRecordsBuffer.free();
    launchParamsBuffer.free();
    asBuffer.free();

    // Destroy OptiX device context
    if (optixContext)
      OPTIX_CHECK(optixDeviceContextDestroy(optixContext));

    // Destroy CUDA stream (and optionally context if you created it manually)
    if (stream)
      cudaStreamDestroy(stream);
  }

  void SampleRenderer::buildAccel(int triangles_vertices_count, uintptr_t triangles_vertices, int triangle_indices_count, uintptr_t triangles_indices)
  {

    OptixTraversableHandle asHandle{0};

    // ==================================================================
    // triangle inputs
    // ==================================================================
    OptixBuildInput triangleInput = {};
    triangleInput.type = OPTIX_BUILD_INPUT_TYPE_TRIANGLES;

    CUdeviceptr d_vertices = CUdeviceptr(triangles_vertices);
    CUdeviceptr d_indices = CUdeviceptr(triangles_indices);

    triangleInput.triangleArray.vertexFormat = OPTIX_VERTEX_FORMAT_FLOAT3;
    triangleInput.triangleArray.vertexStrideInBytes = 3 * sizeof(float);
    triangleInput.triangleArray.numVertices = triangles_vertices_count;
    triangleInput.triangleArray.vertexBuffers = &d_vertices;

    triangleInput.triangleArray.indexFormat = OPTIX_INDICES_FORMAT_UNSIGNED_INT3;
    triangleInput.triangleArray.indexStrideInBytes = 3 * sizeof(int);
    triangleInput.triangleArray.numIndexTriplets = triangle_indices_count;
    triangleInput.triangleArray.indexBuffer = d_indices;

    uint32_t triangleInputFlags[1] = {0};

    // in this example we have one SBT entry, and no per-primitive
    // materials:
    triangleInput.triangleArray.flags = triangleInputFlags;
    triangleInput.triangleArray.numSbtRecords = 1;
    triangleInput.triangleArray.sbtIndexOffsetBuffer = 0;
    triangleInput.triangleArray.sbtIndexOffsetSizeInBytes = 0;
    triangleInput.triangleArray.sbtIndexOffsetStrideInBytes = 0;

    // ==================================================================
    // BLAS setup
    // ==================================================================

    OptixAccelBuildOptions accelOptions = {};
    accelOptions.buildFlags = OPTIX_BUILD_FLAG_NONE | OPTIX_BUILD_FLAG_ALLOW_COMPACTION;
    accelOptions.motionOptions.numKeys = 1;
    accelOptions.operation = OPTIX_BUILD_OPERATION_BUILD;

    OptixAccelBufferSizes blasBufferSizes;
    OPTIX_CHECK(optixAccelComputeMemoryUsage(optixContext,
                                             &accelOptions,
                                             &triangleInput,
                                             1, // num_build_inputs
                                             &blasBufferSizes));

    // ==================================================================
    // prepare compaction
    // ==================================================================

    CUDABuffer compactedSizeBuffer;
    compactedSizeBuffer.alloc(sizeof(uint64_t));

    OptixAccelEmitDesc emitDesc;
    emitDesc.type = OPTIX_PROPERTY_TYPE_COMPACTED_SIZE;
    emitDesc.result = compactedSizeBuffer.d_pointer();

    // ==================================================================
    // execute build (main stage)
    // ==================================================================

    CUDABuffer tempBuffer;
    tempBuffer.alloc(blasBufferSizes.tempSizeInBytes);

    CUDABuffer outputBuffer;
    outputBuffer.alloc(blasBufferSizes.outputSizeInBytes);

    OPTIX_CHECK(optixAccelBuild(optixContext,
                                /* stream */ 0,
                                &accelOptions,
                                &triangleInput,
                                1,
                                tempBuffer.d_pointer(),
                                tempBuffer.sizeInBytes,

                                outputBuffer.d_pointer(),
                                outputBuffer.sizeInBytes,

                                &asHandle,

                                &emitDesc, 1));
    CUDA_SYNC_CHECK();

    // ==================================================================
    // perform compaction
    // ==================================================================
    uint64_t compactedSize;
    compactedSizeBuffer.download(&compactedSize, 1);

    asBuffer.alloc(compactedSize);
    OPTIX_CHECK(optixAccelCompact(optixContext,
                                  /*stream:*/ 0,
                                  asHandle,
                                  asBuffer.d_pointer(),
                                  asBuffer.sizeInBytes,
                                  &asHandle));
    CUDA_SYNC_CHECK();

    // ==================================================================
    // aaaaaand .... clean up
    // ==================================================================
    outputBuffer.free(); // << the UNcompacted, temporary output buffer
    tempBuffer.free();
    compactedSizeBuffer.free();

    // std::cout << "#osc: GAS of triangles built" << std::endl;

    launchParams.traversable = asHandle;
  }

  /*! render one frame */
  void SampleRenderer::nobounce(
      // [numbers]
      int HEIGHT,
      int WIDTH,
      // [input - surfels]
      uintptr_t ptr_surfels_positions,
      uintptr_t ptr_surfels_scales,
      uintptr_t ptr_surfels_quaternions,
      uintptr_t ptr_surfels_opacities,
      // [input - surfels values]
      uintptr_t ptr_surfels_radiances,
      uintptr_t ptr_surfels_emissives,
      uintptr_t ptr_surfels_albedos,
      // [input - rays]
      uintptr_t ptr_rays_origins,
      uintptr_t ptr_rays_directions,
      // [output - results]
      uintptr_t ptr_pixels_hitcounts,
      uintptr_t ptr_pixels_alphas,
      uintptr_t ptr_pixels_distances,
      uintptr_t ptr_pixels_normals,
      // [output - values]
      uintptr_t ptr_pixels_radiances,
      uintptr_t ptr_pixels_emissives,
      uintptr_t ptr_pixels_albedos)
  {
    // [choose raygen]

    const int chosen_raygen_program = 0;
    sbt.raygenRecord = raygenRecordsBuffer.d_pointer() + chosen_raygen_program * sizeof(RaygenRecord);

    // [prepare launchParams]

    launchParams.HEIGHT = HEIGHT;
    launchParams.WIDTH = WIDTH;

    // [input - surfels]

    launchParams.surfels_positions = reinterpret_cast<const float3 *>(ptr_surfels_positions);
    launchParams.surfels_scales = reinterpret_cast<const float2 *>(ptr_surfels_scales);
    launchParams.surfels_quaternions = reinterpret_cast<const float4 *>(ptr_surfels_quaternions);
    launchParams.surfels_opacities = reinterpret_cast<const float *>(ptr_surfels_opacities);
    // values
    launchParams.surfels_radiances = reinterpret_cast<const float3 *>(ptr_surfels_radiances);
    launchParams.surfels_emissives = reinterpret_cast<const float *>(ptr_surfels_emissives);
    launchParams.surfels_albedos = reinterpret_cast<const float3 *>(ptr_surfels_albedos);
    launchParams.surfels_roughnesses = nullptr;
    launchParams.surfels_metallics = nullptr;

    // [input - rays]

    launchParams.rays_origins = reinterpret_cast<const float3 *>(ptr_rays_origins);
    launchParams.rays_directions = reinterpret_cast<const float3 *>(ptr_rays_directions);

    // [output - results]

    launchParams.pixels_hitcounts = reinterpret_cast<int *>(ptr_pixels_hitcounts);

    launchParams.pixels_alphas = reinterpret_cast<float *>(ptr_pixels_alphas);

    launchParams.pixels_distances = reinterpret_cast<float *>(ptr_pixels_distances);
    launchParams.pixels_normals = reinterpret_cast<float3 *>(ptr_pixels_normals);

    // values
    launchParams.pixels_radiances = reinterpret_cast<float3 *>(ptr_pixels_radiances);
    launchParams.pixels_emissives = reinterpret_cast<float *>(ptr_pixels_emissives);
    launchParams.pixels_albedos = reinterpret_cast<float3 *>(ptr_pixels_albedos);

    // [load launchParams]

    launchParamsBuffer.upload(&launchParams, 1);

    // [launch optix]

    OPTIX_CHECK(optixLaunch(/*! pipeline we're launching launch: */
                            pipeline, stream,
                            /*! parameters and SBT */
                            launchParamsBuffer.d_pointer(),
                            launchParamsBuffer.sizeInBytes,
                            &sbt,
                            /*! dimensions of the launch: */
                            WIDTH,
                            HEIGHT,
                            1 // use for loop for path tracing spp, they have the same speeds
                            ));

    // sync - make sure the frame is rendered before we download and
    // display (obviously, for a high-performance application you
    // want to use streams and double-buffering, but for this simple
    // example, this will have to do)
    CUDA_SYNC_CHECK();

    // [complete this round of launch]
  }

  void SampleRenderer::singlebounce(
      // [numbers]
      int HEIGHT,
      int WIDTH,
      int SPP,
      // [input - surfels]
      uintptr_t ptr_surfels_positions,
      uintptr_t ptr_surfels_scales,
      uintptr_t ptr_surfels_quaternions,
      uintptr_t ptr_surfels_opacities,
      // values
      uintptr_t ptr_surfels_radiances,
      uintptr_t ptr_surfels_emissives,
      uintptr_t ptr_surfels_albedos,
      uintptr_t ptr_surfels_roughnesses,
      uintptr_t ptr_surfels_metallics,
      // values end
      // [input - rays]
      uintptr_t ptr_rays_origins,
      uintptr_t ptr_rays_directions,
      // [output - results]
      uintptr_t ptr_pixels_albedos,
      uintptr_t ptr_pixels_rendering_radiances,
      uintptr_t ptr_d_pixels_rendering_radiances_d_P)
  {
    // [choose raygen]

    const int chosen_raygen_program = 1;
    sbt.raygenRecord = raygenRecordsBuffer.d_pointer() + chosen_raygen_program * sizeof(RaygenRecord);

    // [prepare launchParams]

    launchParams.HEIGHT = HEIGHT;
    launchParams.WIDTH = WIDTH;

    launchParams.SPP = SPP;

    // [input - surfels]

    launchParams.surfels_positions = reinterpret_cast<const float3 *>(ptr_surfels_positions);
    launchParams.surfels_scales = reinterpret_cast<const float2 *>(ptr_surfels_scales);
    launchParams.surfels_quaternions = reinterpret_cast<const float4 *>(ptr_surfels_quaternions);
    launchParams.surfels_opacities = reinterpret_cast<const float *>(ptr_surfels_opacities);
    // values
    launchParams.surfels_radiances = reinterpret_cast<const float3 *>(ptr_surfels_radiances);
    launchParams.surfels_emissives = reinterpret_cast<const float *>(ptr_surfels_emissives);
    launchParams.surfels_albedos = reinterpret_cast<const float3 *>(ptr_surfels_albedos);
    launchParams.surfels_roughnesses = reinterpret_cast<const float *>(ptr_surfels_roughnesses);
    launchParams.surfels_metallics = reinterpret_cast<const float *>(ptr_surfels_metallics);

    // [input - rays]

    launchParams.rays_origins = reinterpret_cast<const float3 *>(ptr_rays_origins);
    launchParams.rays_directions = reinterpret_cast<const float3 *>(ptr_rays_directions);

    // [output - results]

    launchParams.pixels_albedos = reinterpret_cast<float3 *>(ptr_pixels_albedos);
    launchParams.pixels_rendering_radiances = reinterpret_cast<float3 *>(ptr_pixels_rendering_radiances);
    launchParams.pixels_d_rendering_radiances_d_P = reinterpret_cast<float3 *>(ptr_d_pixels_rendering_radiances_d_P);

    // [load launchParams]

    launchParamsBuffer.upload(&launchParams, 1);

    // [launch optix]

    OPTIX_CHECK(optixLaunch(/*! pipeline we're launching launch: */
                            pipeline, stream,
                            /*! parameters and SBT */
                            launchParamsBuffer.d_pointer(),
                            launchParamsBuffer.sizeInBytes,
                            &sbt,
                            /*! dimensions of the launch: */
                            WIDTH,
                            HEIGHT,
                            1 // use for loop for path tracing spp, they have the same speeds
                            ));

    // sync - make sure the frame is rendered before we download and
    // display (obviously, for a high-performance application you
    // want to use streams and double-buffering, but for this simple
    // example, this will have to do)
    CUDA_SYNC_CHECK();

    // [complete this round of launch]
  }

  void SampleRenderer::materialpass(
      int HEIGHT, int WIDTH,
      uintptr_t ptr_surfels_positions,
      uintptr_t ptr_surfels_scales,
      uintptr_t ptr_surfels_quaternions,
      uintptr_t ptr_surfels_opacities,
      uintptr_t ptr_surfels_albedos,
      uintptr_t ptr_surfels_roughnesses,
      uintptr_t ptr_surfels_metallics,
      uintptr_t ptr_rays_origins,
      uintptr_t ptr_rays_directions,
      uintptr_t ptr_pixels_basecolors,
      uintptr_t ptr_pixels_roughnesses,
      uintptr_t ptr_pixels_metallics)
  {
    const int chosen_raygen_program = 5;
    sbt.raygenRecord = raygenRecordsBuffer.d_pointer() + chosen_raygen_program * sizeof(RaygenRecord);
    launchParams.HEIGHT = HEIGHT;
    launchParams.WIDTH = WIDTH;
    launchParams.surfels_positions = reinterpret_cast<const float3 *>(ptr_surfels_positions);
    launchParams.surfels_scales = reinterpret_cast<const float2 *>(ptr_surfels_scales);
    launchParams.surfels_quaternions = reinterpret_cast<const float4 *>(ptr_surfels_quaternions);
    launchParams.surfels_opacities = reinterpret_cast<const float *>(ptr_surfels_opacities);
    launchParams.surfels_albedos = reinterpret_cast<const float3 *>(ptr_surfels_albedos);
    launchParams.surfels_roughnesses = reinterpret_cast<const float *>(ptr_surfels_roughnesses);
    launchParams.surfels_metallics = reinterpret_cast<const float *>(ptr_surfels_metallics);
    launchParams.rays_origins = reinterpret_cast<const float3 *>(ptr_rays_origins);
    launchParams.rays_directions = reinterpret_cast<const float3 *>(ptr_rays_directions);
    launchParams.pixels_basecolors = reinterpret_cast<float3 *>(ptr_pixels_basecolors);
    launchParams.pixels_roughnesses = reinterpret_cast<float *>(ptr_pixels_roughnesses);
    launchParams.pixels_metallics = reinterpret_cast<float *>(ptr_pixels_metallics);
    launchParamsBuffer.upload(&launchParams, 1);
    OPTIX_CHECK(optixLaunch(pipeline, stream, launchParamsBuffer.d_pointer(),
                            launchParamsBuffer.sizeInBytes, &sbt, WIDTH, HEIGHT, 1));
    CUDA_SYNC_CHECK();
  }

  void SampleRenderer::materialpass_backward(
      int HEIGHT, int WIDTH,
      uintptr_t ptr_surfels_positions,
      uintptr_t ptr_surfels_scales,
      uintptr_t ptr_surfels_quaternions,
      uintptr_t ptr_surfels_opacities,
      uintptr_t ptr_surfels_albedos,
      uintptr_t ptr_surfels_roughnesses,
      uintptr_t ptr_surfels_metallics,
      uintptr_t ptr_rays_origins,
      uintptr_t ptr_rays_directions,
      uintptr_t ptr_d_L_d_pixels_basecolors,
      uintptr_t ptr_d_L_d_pixels_roughnesses,
      uintptr_t ptr_d_L_d_pixels_metallics,
      uintptr_t ptr_d_L_d_surfels_albedos,
      uintptr_t ptr_d_L_d_surfels_roughnesses,
      uintptr_t ptr_d_L_d_surfels_metallics)
  {
    const int chosen_raygen_program = 6;
    sbt.raygenRecord = raygenRecordsBuffer.d_pointer() + chosen_raygen_program * sizeof(RaygenRecord);
    launchParams.HEIGHT = HEIGHT;
    launchParams.WIDTH = WIDTH;
    launchParams.surfels_positions = reinterpret_cast<const float3 *>(ptr_surfels_positions);
    launchParams.surfels_scales = reinterpret_cast<const float2 *>(ptr_surfels_scales);
    launchParams.surfels_quaternions = reinterpret_cast<const float4 *>(ptr_surfels_quaternions);
    launchParams.surfels_opacities = reinterpret_cast<const float *>(ptr_surfels_opacities);
    launchParams.surfels_albedos = reinterpret_cast<const float3 *>(ptr_surfels_albedos);
    launchParams.surfels_roughnesses = reinterpret_cast<const float *>(ptr_surfels_roughnesses);
    launchParams.surfels_metallics = reinterpret_cast<const float *>(ptr_surfels_metallics);
    launchParams.rays_origins = reinterpret_cast<const float3 *>(ptr_rays_origins);
    launchParams.rays_directions = reinterpret_cast<const float3 *>(ptr_rays_directions);
    launchParams.d_L_d_pixels_basecolors = reinterpret_cast<const float3 *>(ptr_d_L_d_pixels_basecolors);
    launchParams.d_L_d_pixels_roughnesses = reinterpret_cast<const float *>(ptr_d_L_d_pixels_roughnesses);
    launchParams.d_L_d_pixels_metallics = reinterpret_cast<const float *>(ptr_d_L_d_pixels_metallics);
    launchParams.d_L_d_surfels_albedos = reinterpret_cast<float3 *>(ptr_d_L_d_surfels_albedos);
    launchParams.d_L_d_surfels_roughnesses = reinterpret_cast<float *>(ptr_d_L_d_surfels_roughnesses);
    launchParams.d_L_d_surfels_metallics = reinterpret_cast<float *>(ptr_d_L_d_surfels_metallics);
    launchParamsBuffer.upload(&launchParams, 1);
    OPTIX_CHECK(optixLaunch(pipeline, stream, launchParamsBuffer.d_pointer(),
                            launchParamsBuffer.sizeInBytes, &sbt, WIDTH, HEIGHT, 1));
    CUDA_SYNC_CHECK();
  }

  void SampleRenderer::pathtracing(
      // [numbers]
      int HEIGHT,
      int WIDTH,
      int BOUNCE_LIMIT,
      int SPP,
      // [input - surfels]
      uintptr_t ptr_surfels_positions,
      uintptr_t ptr_surfels_scales,
      uintptr_t ptr_surfels_quaternions,
      uintptr_t ptr_surfels_opacities,
      // values
      uintptr_t ptr_surfels_radiances,
      uintptr_t ptr_surfels_emissives,
      uintptr_t ptr_surfels_albedos,
      uintptr_t ptr_surfels_roughnesses,
      uintptr_t ptr_surfels_metallics,
      // values end
      // [input - rays]
      uintptr_t ptr_rays_origins,
      uintptr_t ptr_rays_directions,
      // [output - results]
      uintptr_t ptr_rendering_radiances)
  {
    // [choose raygen]

    const int chosen_raygen_program = 2;
    sbt.raygenRecord = raygenRecordsBuffer.d_pointer() + chosen_raygen_program * sizeof(RaygenRecord);

    // [prepare launchParams]

    launchParams.HEIGHT = HEIGHT;
    launchParams.WIDTH = WIDTH;

    launchParams.SPP = SPP;
    launchParams.BOUNCE_LIMIT = BOUNCE_LIMIT;

    // [input - surfels]

    launchParams.surfels_positions = reinterpret_cast<const float3 *>(ptr_surfels_positions);
    launchParams.surfels_scales = reinterpret_cast<const float2 *>(ptr_surfels_scales);
    launchParams.surfels_quaternions = reinterpret_cast<const float4 *>(ptr_surfels_quaternions);
    launchParams.surfels_opacities = reinterpret_cast<const float *>(ptr_surfels_opacities);
    // values
    launchParams.surfels_radiances = reinterpret_cast<const float3 *>(ptr_surfels_radiances);
    launchParams.surfels_emissives = reinterpret_cast<const float *>(ptr_surfels_emissives);
    launchParams.surfels_albedos = reinterpret_cast<const float3 *>(ptr_surfels_albedos);
    launchParams.surfels_roughnesses = reinterpret_cast<const float *>(ptr_surfels_roughnesses);
    launchParams.surfels_metallics = reinterpret_cast<const float *>(ptr_surfels_metallics);

    // [input - rays]

    launchParams.rays_origins = reinterpret_cast<const float3 *>(ptr_rays_origins);
    launchParams.rays_directions = reinterpret_cast<const float3 *>(ptr_rays_directions);

    // [output - results]

    launchParams.pixels_rendering_radiances = reinterpret_cast<float3 *>(ptr_rendering_radiances);

    // [load launchParams]

    launchParamsBuffer.upload(&launchParams, 1);

    // [launch optix]

    OPTIX_CHECK(optixLaunch(/*! pipeline we're launching launch: */
                            pipeline, stream,
                            /*! parameters and SBT */
                            launchParamsBuffer.d_pointer(),
                            launchParamsBuffer.sizeInBytes,
                            &sbt,
                            /*! dimensions of the launch: */
                            WIDTH,
                            HEIGHT,
                            1 // use for loop for path tracing spp, they have the same speeds
                            ));

    // sync - make sure the frame is rendered before we download and
    // display (obviously, for a high-performance application you
    // want to use streams and double-buffering, but for this simple
    // example, this will have to do)
    CUDA_SYNC_CHECK();

    // [complete this round of launch]
  }

  void SampleRenderer::nobounce_backward(
      // [numbers]
      int HEIGHT,
      int WIDTH,
      // [input - surfels]
      uintptr_t ptr_surfels_positions,
      uintptr_t ptr_surfels_scales,
      uintptr_t ptr_surfels_quaternions,
      uintptr_t ptr_surfels_opacities,
      // values
      uintptr_t ptr_surfels_radiances,
      uintptr_t ptr_surfels_emissives,
      uintptr_t ptr_surfels_albedos,
      // [input - rays]
      uintptr_t ptr_rays_origins,
      uintptr_t ptr_rays_directions,
      // [backward - input - forward results]
      uintptr_t ptr_pixels_radiances,
      uintptr_t ptr_pixels_emissives,
      uintptr_t ptr_pixels_alphas,
      uintptr_t ptr_pixels_normals,
      uintptr_t ptr_pixels_distances,
      // [backward - input - pytorch gradients]
      uintptr_t ptr_d_L_d_pixels_radiances,
      uintptr_t ptr_d_L_d_pixels_emissives,
      uintptr_t ptr_d_L_d_pixels_alphas,
      uintptr_t ptr_d_L_d_pixels_normals,
      uintptr_t ptr_d_L_d_pixels_distances,
      // [backward: output]
      uintptr_t ptr_d_L_d_surfels_radiances,
      uintptr_t ptr_d_L_d_surfels_emissives,
      uintptr_t ptr_d_L_d_surfels_opacities,
      uintptr_t ptr_d_L_d_surfels_scales,
      uintptr_t ptr_d_L_d_surfels_positions,
      uintptr_t ptr_d_L_d_surfels_quaternions)
  {
    // [choose raygen]

    const int chosen_raygen_program = 3;
    sbt.raygenRecord = raygenRecordsBuffer.d_pointer() + chosen_raygen_program * sizeof(RaygenRecord);

    // [prepare launchParams]

    launchParams.HEIGHT = HEIGHT;
    launchParams.WIDTH = WIDTH;

    // [input - surfels]

    launchParams.surfels_positions = reinterpret_cast<const float3 *>(ptr_surfels_positions);
    launchParams.surfels_scales = reinterpret_cast<const float2 *>(ptr_surfels_scales);
    launchParams.surfels_quaternions = reinterpret_cast<const float4 *>(ptr_surfels_quaternions);
    launchParams.surfels_opacities = reinterpret_cast<const float *>(ptr_surfels_opacities);
    // values
    launchParams.surfels_radiances = reinterpret_cast<const float3 *>(ptr_surfels_radiances);
    launchParams.surfels_emissives = reinterpret_cast<const float *>(ptr_surfels_emissives);
    launchParams.surfels_albedos = reinterpret_cast<const float3 *>(ptr_surfels_albedos);

    // [input - rays]

    launchParams.rays_origins = reinterpret_cast<const float3 *>(ptr_rays_origins);
    launchParams.rays_directions = reinterpret_cast<const float3 *>(ptr_rays_directions);

    // [backward - input]

    launchParams.backward_pixels_radiances = reinterpret_cast<const float3 *>(ptr_pixels_radiances);
    launchParams.backward_pixels_emissives = reinterpret_cast<const float *>(ptr_pixels_emissives);
    launchParams.backward_pixels_alphas = reinterpret_cast<const float *>(ptr_pixels_alphas);
    launchParams.backward_pixels_normals = reinterpret_cast<const float3 *>(ptr_pixels_normals);
    launchParams.backward_pixels_distances = reinterpret_cast<const float *>(ptr_pixels_distances);

    launchParams.d_L_d_pixels_radiances = reinterpret_cast<const float3 *>(ptr_d_L_d_pixels_radiances);
    launchParams.d_L_d_pixels_emissives = reinterpret_cast<const float *>(ptr_d_L_d_pixels_emissives);
    launchParams.d_L_d_pixels_alphas = reinterpret_cast<const float *>(ptr_d_L_d_pixels_alphas);
    launchParams.d_L_d_pixels_normals = reinterpret_cast<const float3 *>(ptr_d_L_d_pixels_normals);
    launchParams.d_L_d_pixels_distances = reinterpret_cast<const float *>(ptr_d_L_d_pixels_distances);

    // [backward - output]

    launchParams.d_L_d_surfels_radiances = reinterpret_cast<float3 *>(ptr_d_L_d_surfels_radiances);
    launchParams.d_L_d_surfels_emissives = reinterpret_cast<float *>(ptr_d_L_d_surfels_emissives);
    launchParams.d_L_d_surfels_opacities = reinterpret_cast<float *>(ptr_d_L_d_surfels_opacities);
    launchParams.d_L_d_surfels_scales = reinterpret_cast<float2 *>(ptr_d_L_d_surfels_scales);
    launchParams.d_L_d_surfels_positions = reinterpret_cast<float3 *>(ptr_d_L_d_surfels_positions);
    launchParams.d_L_d_surfels_quaternions = reinterpret_cast<float4 *>(ptr_d_L_d_surfels_quaternions);

    // [load launchParams]

    launchParamsBuffer.upload(&launchParams, 1);

    // [launch optix]

    OPTIX_CHECK(optixLaunch(/*! pipeline we're launching launch: */
                            pipeline, stream,
                            /*! parameters and SBT */
                            launchParamsBuffer.d_pointer(),
                            launchParamsBuffer.sizeInBytes,
                            &sbt,
                            /*! dimensions of the launch: */
                            WIDTH,
                            HEIGHT,
                            1 // use for loop for path tracing spp, they have the same speeds
                            ));

    // sync - make sure the frame is rendered before we download and
    // display (obviously, for a high-performance application you
    // want to use streams and double-buffering, but for this simple
    // example, this will have to do)
    CUDA_SYNC_CHECK();

    // [complete this round of launch]
  }

  void SampleRenderer::singlebounce_backward(
      // [numbers]
      int HEIGHT,
      int WIDTH,
      // [input - surfels]
      uintptr_t ptr_surfels_positions,
      uintptr_t ptr_surfels_scales,
      uintptr_t ptr_surfels_quaternions,
      uintptr_t ptr_surfels_opacities,
      // values
      uintptr_t ptr_surfels_radiances,
      uintptr_t ptr_surfels_emissives,
      uintptr_t ptr_surfels_albedos,
      // [input - rays]
      uintptr_t ptr_rays_origins,
      uintptr_t ptr_rays_directions,
      // [backward - input - forward results]
      uintptr_t ptr_pixels_albedos,
      uintptr_t ptr_pixels_rendering_radiances,
      uintptr_t ptr_d_pixels_rendering_radiances_d_P,
      // [backward - input - pytorch gradients]
      uintptr_t ptr_d_L_d_pixels_rendering_radiances,
      // [backward: output]
      uintptr_t ptr_d_L_d_surfels_albedos)
  {
    // [choose raygen]

    const int chosen_raygen_program = 4;
    sbt.raygenRecord = raygenRecordsBuffer.d_pointer() + chosen_raygen_program * sizeof(RaygenRecord);

    // [prepare launchParams]

    launchParams.HEIGHT = HEIGHT;
    launchParams.WIDTH = WIDTH;

    // [input - surfels]

    launchParams.surfels_positions = reinterpret_cast<const float3 *>(ptr_surfels_positions);
    launchParams.surfels_scales = reinterpret_cast<const float2 *>(ptr_surfels_scales);
    launchParams.surfels_quaternions = reinterpret_cast<const float4 *>(ptr_surfels_quaternions);
    launchParams.surfels_opacities = reinterpret_cast<const float *>(ptr_surfels_opacities);
    // values
    launchParams.surfels_radiances = reinterpret_cast<const float3 *>(ptr_surfels_radiances);
    launchParams.surfels_emissives = reinterpret_cast<const float *>(ptr_surfels_emissives);
    launchParams.surfels_albedos = reinterpret_cast<const float3 *>(ptr_surfels_albedos);

    // [input - rays]

    launchParams.rays_origins = reinterpret_cast<const float3 *>(ptr_rays_origins);
    launchParams.rays_directions = reinterpret_cast<const float3 *>(ptr_rays_directions);

    // [backward - input]

    launchParams.backward_pixels_albedos = reinterpret_cast<const float3 *>(ptr_pixels_albedos);
    launchParams.backward_pixels_rendering_radiances = reinterpret_cast<const float3 *>(ptr_pixels_rendering_radiances);
    launchParams.backward_pixels_d_rendering_radiances_d_P = reinterpret_cast<const float3 *>(ptr_d_pixels_rendering_radiances_d_P);

    launchParams.d_L_d_pixels_rendering_radiances = reinterpret_cast<const float3 *>(ptr_d_L_d_pixels_rendering_radiances);

    // [backward - output]

    launchParams.d_L_d_surfels_albedos = reinterpret_cast<float3 *>(ptr_d_L_d_surfels_albedos);

    // [load launchParams]

    launchParamsBuffer.upload(&launchParams, 1);

    // [launch optix]

    OPTIX_CHECK(optixLaunch(/*! pipeline we're launching launch: */
                            pipeline, stream,
                            /*! parameters and SBT */
                            launchParamsBuffer.d_pointer(),
                            launchParamsBuffer.sizeInBytes,
                            &sbt,
                            /*! dimensions of the launch: */
                            WIDTH,
                            HEIGHT,
                            1 // use for loop for path tracing spp, they have the same speeds
                            ));

    // sync - make sure the frame is rendered before we download and
    // display (obviously, for a high-performance application you
    // want to use streams and double-buffering, but for this simple
    // example, this will have to do)
    CUDA_SYNC_CHECK();

    // [complete this round of launch]
  }
} // ::osc
